[tool.poetry]
name = "curses_stars"
version = "0.1.0"
description = "Small game to study async programming."
authors = ["Aleksei Panfilov"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
